name: Generate Database

on:
  push:
    branches:
      - main
    paths:
      - 'DETAILS/**'
      - 'LOGOS/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pytz 

      - name: Run Database Generator
        run: python generate_json.py

      - name: Commit and Push Database
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add database.json
          git commit -m "Automated update: Database and Channel Timestamps" || exit 0
          git push
